name: tankobon
description: TankÅbon - a Flutter manga reader app.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.0.2  <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.1.2
  logging: ^1.2.0
  flutter_native_splash: ^2.2.19
  auto_route: ^7.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.14
  flutter_platform_widgets: ^3.3.2
  cupertino_icons: ^1.0.5
  photo_view: ^0.14.0
  flutter_svg: ^2.0.5
  slang: ^3.18.1
  slang_flutter: ^3.17.0
  riverpod_annotation: ^2.1.1
  jwt_decoder: ^2.0.1
  image_size_getter: ^2.1.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.2
  freezed: ^2.3.4
  auto_route_generator: ^7.1.1
  flutter_launcher_icons: ^0.13.1
  slang_build_runner: ^3.17.0
  widgetbook: ^3.0.0-rc.1
  dart_code_metrics: ^5.7.4
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/theme_light.json
    - assets/theme_dark.json

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#FFE9DB"
  adaptive_icon_foreground: assets/icon/icon_foreground.png

flutter_native_splash:
  color: "#FFE9DB"
  image: assets/icon/icon_foreground.png
  color_dark: "#1F1F20"
  image_dark: assets/icon/icon_foreground_dark.png
  android_12:
    image: assets/icon/icon_foreground.png
    icon_background_color: "#FFE9DB"
    image_dark: assets/icon/icon_foreground_dark.png
    icon_background_color_dark: "#1F1F20"
  web: false

flutter_gen:
  line_length: 80
  integrations:
    flutter_svg: true
