name: tankobon
description: TankÅbon - a flutter manga reader app
homepage: https://aspirin.moe
repository: https://github.com/ASPIRINmoe/tankobon-flutter

version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  transparent_image: ^2.0.0
  flutter_hooks: ^0.18.4
  photo_view: ^0.13.0
  layout: ^1.0.2
  flutter_staggered_animations: ^1.0.0
  dio: ^4.0.6
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  injectable: ^1.5.3
  data_channel: ^2.0.0+1
  connectivity_plus: ^2.3.0
  freezed_annotation: ^2.0.3
  widgetbook: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

