name: tankobon
description: TankÅbon - a Flutter manga reader app.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  intl: ^0.17.0
  auto_route: ^5.0.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  provider: ^6.0.3
  flutter_hooks: ^0.18.5+1
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  isar: ^3.0.0-dev.13
  isar_flutter_libs: ^3.0.0-dev.9
  dio: ^4.0.6
  path_provider: ^2.0.11
  flutter_platform_widgets: ^2.0.0
  cupertino_icons: ^1.0.5
  transparent_image: ^2.0.0
  dartx: ^1.1.0
  collection: ^1.16.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  mobx_codegen: ^2.0.7
  isar_generator: ^3.0.0-dev.10
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  auto_route_generator: ^5.0.1
  flutter_launcher_icons: ^0.10.0
  widgetbook: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#FFE9DB"
  adaptive_icon_foreground: assets/icon/icon_foreground.png

flutter_native_splash:
  color: "#FFE9DB"
  image: assets/icon/icon_foreground.png
  color_dark: "#1F1F20"
  image_dark: assets/icon/icon_foreground_dark.png
  android_12:
    image: assets/icon/icon_foreground.png
    icon_background_color: "#FFE9DB"
    image_dark: assets/icon/icon_foreground_dark.png
    icon_background_color_dark: "#1F1F20"
  web: false

flutter_gen:
  line_length: 80
  integrations:
    flutter_svg: true